project:
  type: website
  output-dir: docs

resources: 
  - media/*

lang: en
website: 
  title: "Open Science and Reproducibility with Quarto, GitHub, and R 2025"
  site-url: https://www.ekotov.pro/2025-EDSD-open-science-quarto-github/
  repo-url: https://github.com/e-kotov/2025-EDSD-open-science-quarto-github
  open-graph:
    title: "Open Science and Reproducibility with Quarto, GitHub, and R 2025"
    description: "This website provides supporting materials for the workshop 'Open Science and Reproducibility with Quarto, GitHub, and R' which is part of the European Doctoral School of Demography (EDSD) 2025 preparatory courses hosted by the Max Planck Institute for Demographic Researc (Rostock, Germany)."
  page-navigation: true
  page-footer: 
      border: true
      left: "Author: Egor Kotov" 
      center:
        - text: "CC-BY-SA 4.0"
          href: https://creativecommons.org/licenses/by-sa/4.0/
      right: 
        - icon: github
          href: https://www.ekotov.pro/2025-EDSD-open-science-quarto-github/

  sidebar:
    title: "Open Science and Reproducibility with Quarto, GitHub, and R 2025"
    style: "docked"
    search: true
    tools: 
      - icon: github
        text: Github
        href: https://github.com/e-kotov/2025-EDSD-open-science-quarto-github
    contents:
      - index.qmd
      - setup.qmd
      - task.qmd
      - section: "Learn more"
        contents:
          - href: "https://rstudio-conf-2022.github.io/get-started-quarto/"
            target: "_blank"
            text: "...learn more about Quarto in advanced Quarto workshop by Posit"
          - href: "https://www.ekotov.pro/2025-mpidr-open-science-reproducible-workflows/"
            target: "_blank"
            text: "...learn more about reproducible workflows in R with with package managers, containers and pipeline control tools"




format:
  html:
    link-external-icon: true
    link-external-newwindow: true
    link-external-filter: 'ekotov\.pro'
    include-in-header:
      - text: |
          <!-- tell Zotero this is a webpage via Dublin Core -->
          <meta name="DC.Type" content="WebPage">
      - file: media/analytics.html
    theme:
      light: zephyr
      dark: slate
    css: styles.css
    toc: true
    toc-depth: 4
    toc-expand: 4
    toc-location: right
    code-overflow: wrap
    grid:
      body-width: 800px
    mermaid:
      theme: neutral

bibliography: references.bib
bibliographystyle: apa

citation:
  type: webpage
  title: "Open Science and Reproducibility with Quarto, GitHub, and R 2025"
  issued: 2025-10-21
  doi: 10.5281/zenodo.17401408
doi: 10.5281/zenodo.17401408
google-scholar: true

editor: source

editor_options:
  markdown:
    wrap: 72
    canonical: true

execute:
  freeze: auto


authors:
  - name: Egor Kotov
    url: https://www.ekotov.pro/
    orcid: 0000-0001-6690-5345
    affiliations:
      - ref: mpidr
      - ref: upf

affiliations:
  - id: mpidr
    name: Max Planck Institute for Demographic Research
    city: Rostock
    country: Germany
    url: https://www.demogr.mpg.de/en
  - id: upf
    name: Universitat Pompeu Fabra
    city: Barcelona
    country: Spain
    url: https://www.upf.edu/en/web/politiques/home
